language: swift
osx_image: xcode11.6
before_install:
- cp TripKit/secrets.json.template TripKit/secrets.json
script: set -o pipefail && xcodebuild -workspace TripKit.xcworkspace -scheme TripKit\ iOS -destination platform\=iOS\ Simulator,OS\=13.6,name\=iPhone\ 11\ Pro build | xcpretty
