language: swift
osx_image: xcode11.6
before_install:
- openssl aes-256-cbc -K $encrypted_fb088dcee1f3_key -iv $encrypted_fb088dcee1f3_iv -in Sources/TripKit/secrets.json.enc -out Sources/TripKit/secrets.json -d
install: swift package update
script:
- set -o pipefail 
- xcodebuild -scheme "TripKit iOS" -destination "platform=iOS Simulator,OS=13.6,name=iPhone 11 Pro" build-for-testing test | xcpretty
- xcodebuild -scheme "TripKit watchOS" -destination "platform=watchOS Simulator,OS=6.2.1,name=Apple Watch Series 5 - 44mm" build | xcpretty
- xcodebuild -scheme "TripKit tvOS" -destination "platform=tvOS Simulator,OS=13.3,name=Apple TV 4K" build | xcpretty
- xcodebuild -scheme "TripKit macOS" -destination "platform=macOS" build | xcpretty
