name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build
    - name: Decrypt secrets
      run: ./.github/scripts/decrypt_secret.sh
      env:
        SECRETS_PASSPHRASE: ${{ secrets.SECRETS_PASSPHRASE }}
    - name: Run tests
      run: swift test
      continue-on-error: true
