name: Live Provider Test

on:
  schedule:
    - cron: '0 8 1 * *'
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  LiveTests:
    runs-on: macos-14
    name: Live tests
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt secrets
        run: ./.github/scripts/decrypt_secret.sh
        env:
          SECRETS_PASSPHRASE: ${{ secrets.SECRETS_PASSPHRASE }}
      - name: Test
        run: |
          xcodebuild -scheme "TripKitTests macOS" -resultBundlePath LiveTestResults -test-iterations 3 -retry-tests-on-failure test
      - uses: kishikawakatsumi/xcresulttool@v1.3.0
        with:
          path: LiveTestResults.xcresult
          title: Live test results
        if: success() || failure()
