name: Fixtures Test

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: macos-11
    name: Test
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt secrets
        run: ./.github/scripts/decrypt_secret.sh
        env:
          SECRETS_PASSPHRASE: ${{ secrets.SECRETS_PASSPHRASE }}
      - name: Test
        run: |
          xcodebuild -scheme "StaticTripKitTests macOS" -resultBundlePath FixturesTestResults test
      - uses: kishikawakatsumi/xcresulttool@v1.0.5
        with:
          path: FixturesTestResults.xcresult
          title: Fixtures test results
        if: success() || failure()