name: Provider tests

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: fwal/setup-swift@v1
    - name: Get swift version
      run: swift --version
    - name: Decrypt secrets
      run: ./.github/scripts/decrypt_secret.sh
      env:
        SECRETS_PASSPHRASE: ${{ secrets.SECRETS_PASSPHRASE }}
    - name: Build
      run: swift build
    - name: Test
      run: swift test --filter TripKitTests
