name: Provider tests

on:
  schedule:
    - cron: '0 0 * * 0'
  create

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Decrypt secrets
      run: ./.github/scripts/decrypt_secret.sh
      env:
        SECRETS_PASSPHRASE: ${{ secrets.SECRETS_PASSPHRASE }}
    - name: Build
      run: swift build
    - name: Test
      run: swift test --filter TripKitTests --skip TripKitTests.TripKitProviderTestCase
