name: Static tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Decrypt secrets
      run: ./.github/scripts/decrypt_secret.sh
      env:
        SECRETS_PASSPHRASE: ${{ secrets.SECRETS_PASSPHRASE }}
    - name: Get swift version
      run: swift --version
    - name: Build
      run: swift build
    - name: Test
      run: swift test --filter StaticTripKitTests
